// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Personalaffe.Infrastructure.Persistence;

#nullable disable

namespace Personalaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalaffeDbContext))]
    [Migration("20260914203436_TheFilesAndTheFolders")]
    partial class TheFilesAndTheFolders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Personalaffe.Domain.AgentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_issued_at");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("token_prefix");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Permissions", "Personalaffe.Domain.AgentAccess.Permissions#Permissions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Files")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("files");

                            b1.Property<string>("Knowledge")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("knowledge");

                            b1.Property<string>("Scratchpad")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scratchpad");

                            b1.Property<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tasks");
                        });

                    b.HasKey("Id")
                        .HasName("pk_agent_access");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("agent_access_token_hash");

                    b.ToTable("agent_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_access_files", "files in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_knowledge", "knowledge in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_scratchpad", "scratchpad in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_tasks", "tasks in ('none', 'read', 'read_write')");
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.ApplicationState", b =>
                {
                    b.Property<string>("Application")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("application");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Application")
                        .HasName("pk_application");

                    b.ToTable("application", (string)null);

                    b.HasData(
                        new
                        {
                            Application = "scratchpad",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "knowledge",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "tasks",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "files",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_secret_hash");

                    b.ToTable("browser_session", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_folders_parent_id");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_files_folder_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PendingTotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("pending_totp_secret");

                    b.Property<DateTimeOffset?>("PendingTotpSecretAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_totp_secret_at");

                    b.Property<DateTimeOffset?>("RecoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset?>("TotpEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enrolled_at");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_owner");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("owner_singleton");

                    b.ToTable("owner", null, t =>
                        {
                            t.HasCheckConstraint("ck_owner_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_recovery_code");

                    b.HasIndex("OwnerId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("recovery_code_hash");

                    b.ToTable("recovery_code", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Scratchpad.ScratchpadEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean")
                        .HasColumnName("pinned");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scratchpad_entries");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_scratchpad_entries_created_at");

                    b.HasIndex("Pinned", "UpdatedAt")
                        .HasDatabaseName("ix_scratchpad_entries_pinned_updated_at");

                    b.ToTable("scratchpad_entries", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.BrowserSession", b =>
                {
                    b.HasOne("Personalaffe.Domain.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_owner");
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.Folder", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("FolderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("FolderId");

                            b1.ToTable("folders");

                            b1.WithOwner()
                                .HasForeignKey("FolderId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.StoredFile", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("StoredFileId");

                            b1.ToTable("files");

                            b1.WithOwner()
                                .HasForeignKey("StoredFileId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.RecoveryCode", b =>
                {
                    b.HasOne("Personalaffe.Domain.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_code_owner");
                });
#pragma warning restore 612, 618
        }
    }
}
