// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Personalaffe.Infrastructure.Persistence;

#nullable disable

namespace Personalaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalaffeDbContext))]
    [Migration("20260920212515_TheBookmarkSearch")]
    partial class TheBookmarkSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Personalaffe.Domain.AgentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_issued_at");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("token_prefix");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Permissions", "Personalaffe.Domain.AgentAccess.Permissions#Permissions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bookmarks")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("none")
                                .HasColumnName("bookmarks");

                            b1.Property<string>("Files")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("files");

                            b1.Property<string>("Knowledge")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("knowledge");

                            b1.Property<string>("Scratchpad")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scratchpad");

                            b1.Property<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tasks");
                        });

                    b.HasKey("Id")
                        .HasName("pk_agent_access");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("agent_access_token_hash");

                    b.ToTable("agent_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_access_bookmarks", "bookmarks in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_files", "files in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_knowledge", "knowledge in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_scratchpad", "scratchpad in ('none', 'read', 'read_write')");

                            t.HasCheckConstraint("ck_agent_access_tasks", "tasks in ('none', 'read', 'read_write')");
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.Appearance.InstanceAppearance", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("colour");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shape");

                    b.Property<string>("Title")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Singleton")
                        .HasName("pk_instance_appearance");

                    b.ToTable("instance_appearance", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_appearance_singleton", "singleton");
                        });

                    b.HasData(
                        new
                        {
                            Singleton = true,
                            Colour = "violet",
                            Shape = "square",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.ApplicationState", b =>
                {
                    b.Property<string>("Application")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("application");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Application")
                        .HasName("pk_application");

                    b.ToTable("application", (string)null);

                    b.HasData(
                        new
                        {
                            Application = "scratchpad",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "knowledge",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "tasks",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "files",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Application = "bookmarks",
                            Enabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("FavoritePosition")
                        .HasColumnType("double precision")
                        .HasColumnName("favorite_position");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<bool>("PrivateOrigin")
                        .HasColumnType("boolean")
                        .HasColumnName("private_origin");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', regexp_replace(coalesce(title, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('simple', coalesce(description, '')), 'B') || setweight(to_tsvector('simple', regexp_replace(coalesce(url, ''), '[^[:alnum:]]+', ' ', 'g')), 'B')", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("FolderId");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_bookmarks_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<bool>("PrivateOrigin")
                        .HasColumnType("boolean")
                        .HasColumnName("private_origin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookmark_folders");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("ParentId");

                    b.ToTable("bookmark_folders", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkOpenDay", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookmark_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("LastOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_opened_at");

                    b.HasKey("BookmarkId", "Day");

                    b.HasIndex("Day");

                    b.ToTable("bookmark_open_days", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkOpening", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookmarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookmark_id");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkId");

                    b.ToTable("bookmark_openings", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_secret_hash");

                    b.ToTable("browser_session", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Dashboard.TileState", b =>
                {
                    b.Property<string>("Tile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tile");

                    b.Property<bool>("Shown")
                        .HasColumnType("boolean")
                        .HasColumnName("shown");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Tile")
                        .HasName("pk_dashboard_tile");

                    b.ToTable("dashboard_tile", (string)null);

                    b.HasData(
                        new
                        {
                            Tile = "tasks",
                            Shown = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Tile = "knowledge",
                            Shown = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Tile = "scratchpad",
                            Shown = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Tile = "files",
                            Shown = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Tile = "weather",
                            Shown = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_folders_parent_id");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', regexp_replace(coalesce(name, ''), '[^[:alnum:]]+', ' ', 'g')), 'A')", true);

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_files_folder_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_files_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Knowledge.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', regexp_replace(coalesce(title, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('simple', coalesce(markdown, '')), 'B')", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_pages_parent_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_pages_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Knowledge.PageRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_page_revisions");

                    b.HasIndex("PageId", "At")
                        .HasDatabaseName("ix_page_revisions_page_id_at");

                    b.ToTable("page_revisions", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.MaintenancePause", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.Property<DateTimeOffset?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Singleton")
                        .HasName("pk_maintenance_pause");

                    b.ToTable("maintenance_pause", null, t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_pause_singleton", "singleton");
                        });

                    b.HasData(
                        new
                        {
                            Singleton = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PendingTotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("pending_totp_secret");

                    b.Property<DateTimeOffset?>("PendingTotpSecretAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_totp_secret_at");

                    b.Property<DateTimeOffset?>("RecoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset?>("TotpEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enrolled_at");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_owner");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("owner_singleton");

                    b.ToTable("owner", null, t =>
                        {
                            t.HasCheckConstraint("ck_owner_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Personalaffe.Domain.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_recovery_code");

                    b.HasIndex("OwnerId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("recovery_code_hash");

                    b.ToTable("recovery_code", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Scratchpad.ScratchpadEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean")
                        .HasColumnName("pinned");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', coalesce(text, '')), 'B')", true);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scratchpad_entries");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_scratchpad_entries_created_at");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_scratchpad_entries_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("Pinned", "UpdatedAt")
                        .HasDatabaseName("ix_scratchpad_entries_pinned_updated_at");

                    b.ToTable("scratchpad_entries", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Tasks.PersonalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', regexp_replace(coalesce(title, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('simple', coalesce(description, '')), 'B')", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_tasks_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("ListId", "Position")
                        .HasDatabaseName("ix_tasks_list_id_position");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Tasks.TaskList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_lists");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at is not null");

                    b.ToTable("task_lists", (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Weather.WeatherPlace", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("units");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Singleton")
                        .HasName("pk_weather_place");

                    b.ToTable("weather_place", null, t =>
                        {
                            t.HasCheckConstraint("ck_weather_place_singleton", "singleton");
                        });

                    b.HasData(
                        new
                        {
                            Singleton = true,
                            Units = "metric",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Personalaffe.Infrastructure.Persistence.FoundRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("Rank")
                        .HasColumnType("real")
                        .HasColumnName("rank");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("Within")
                        .HasColumnType("uuid")
                        .HasColumnName("within");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.Bookmark", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("BookmarkId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("BookmarkId");

                            b1.ToTable("bookmarks");

                            b1.WithOwner()
                                .HasForeignKey("BookmarkId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkFolder", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("BookmarkFolderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("BookmarkFolderId");

                            b1.ToTable("bookmark_folders");

                            b1.WithOwner()
                                .HasForeignKey("BookmarkFolderId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkOpenDay", b =>
                {
                    b.HasOne("Personalaffe.Domain.Bookmarks.Bookmark", null)
                        .WithMany()
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Personalaffe.Domain.Bookmarks.BookmarkOpening", b =>
                {
                    b.HasOne("Personalaffe.Domain.Bookmarks.Bookmark", null)
                        .WithMany()
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Personalaffe.Domain.BrowserSession", b =>
                {
                    b.HasOne("Personalaffe.Domain.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_owner");
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.Folder", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("FolderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("FolderId");

                            b1.ToTable("folders");

                            b1.WithOwner()
                                .HasForeignKey("FolderId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Files.StoredFile", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("StoredFileId");

                            b1.ToTable("files");

                            b1.WithOwner()
                                .HasForeignKey("StoredFileId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Knowledge.Page", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("PageId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("PageId");

                            b1.ToTable("pages");

                            b1.WithOwner()
                                .HasForeignKey("PageId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Knowledge.PageRevision", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "By", b1 =>
                        {
                            b1.Property<Guid>("PageRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("by_name");

                            b1.HasKey("PageRevisionId");

                            b1.ToTable("page_revisions");

                            b1.WithOwner()
                                .HasForeignKey("PageRevisionId");
                        });

                    b.Navigation("By")
                        .IsRequired();
                });

            modelBuilder.Entity("Personalaffe.Domain.RecoveryCode", b =>
                {
                    b.HasOne("Personalaffe.Domain.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_code_owner");
                });

            modelBuilder.Entity("Personalaffe.Domain.Tasks.PersonalTask", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("PersonalTaskId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("PersonalTaskId");

                            b1.ToTable("tasks");

                            b1.WithOwner()
                                .HasForeignKey("PersonalTaskId");
                        });

                    b.Navigation("DeletedBy");
                });

            modelBuilder.Entity("Personalaffe.Domain.Tasks.TaskList", b =>
                {
                    b.OwnsOne("Personalaffe.Domain.Actor", "DeletedBy", b1 =>
                        {
                            b1.Property<Guid>("TaskListId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("deleted_by_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("deleted_by_kind");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by_name");

                            b1.HasKey("TaskListId");

                            b1.ToTable("task_lists");

                            b1.WithOwner()
                                .HasForeignKey("TaskListId");
                        });

                    b.Navigation("DeletedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
