import { test, expect } from "@playwright/test";
import { signedIn, switchApplication } from "./theInstance";

test("saved links can be added, pinned, ordered and opened directly", async ({ page }) => {
  await signedIn(page);
  await switchApplication(page, "bookmarks", true);
  await page.goto("/bookmarks");
  const title = `Browser link ${Date.now()}`;
  await page.getByRole("button", { name: "Add bookmark", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("URL", { exact: true }).fill("https://example.com/bookmarks");
  await dialog.getByLabel("Title", { exact: true }).fill(title);
  await dialog.getByRole("button", { name: "Add bookmark", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const recent = page.getByRole("region", { name: "Recently added" });
  await recent.getByRole("button", { name: `Pin ${title}`, exact: true }).click();
  const favorite = page.getByRole("region", { name: "Favorites" });
  await expect(favorite.getByRole("link", { name: new RegExp(title) })).toHaveAttribute("href", "https://example.com/bookmarks");
  await expect(favorite.getByRole("button", { name: `Move ${title} later`, exact: true })).toBeVisible();
  // Stop at the target boundary; recording must still happen independently.
  await page.context().route("https://example.com/**", (route) => route.fulfill({ body: "Saved link target" }));
  const recorded = page.waitForResponse((response) => response.url().endsWith("/open") && response.request().method() === "POST");
  const popup = page.waitForEvent("popup");
  await favorite.getByRole("link", { name: new RegExp(title) }).click();
  expect((await recorded).ok()).toBeTruthy();
  await (await popup).close();
});

test("private mode clears private cards and resets on reload at phone width", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const folderResponse = await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Private ${Date.now()}`, parent: null, private: true } });
  expect(folderResponse.ok()).toBeTruthy();
  const folder = await folderResponse.json();
  const title = `Hidden browser link ${Date.now()}`;
  const created = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/private", description: "", folder: folder.id } });
  expect(created.ok()).toBeTruthy();
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto("/bookmarks");
  await expect(page.getByRole("heading", { name: "Recently added" })).toBeVisible();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole("button", { name: "Private mode on", exact: true }).last().click();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Private mode off", exact: true })).toBeVisible();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
});

test("management preserves private inheritance, checks stale edits, and restores deletions", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const parent = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Private tree ${Date.now()}`, parent: null, private: true } })).json();
  const child = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: "Inherited", parent: parent.id, private: false } })).json();
  const title = `Managed link ${Date.now()}`;
  const changedTitle = `${title} changed`;
  const create = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/" + "long-path".repeat(60), description: "", folder: child.id } });
  expect(create.ok()).toBeTruthy(); const bookmark = await create.json();
  await page.goto("/bookmarks/manage");
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByLabel("Bookmark folder", { exact: true }).selectOption(child.id);
  await expect(page.getByText(/Private \(inherited\)/)).toBeVisible();
  await page.getByRole("button", { name: `Edit ${title}`, exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Title", { exact: true }).fill("My current edit");
  const other = await page.request.put(`/api/bookmarks/${bookmark.id}`, { headers: { ...headers, "If-Match": create.headers()["etag"] }, data: { title: changedTitle, url: bookmark.url, description: "", folder: child.id } });
  expect(other.ok()).toBeTruthy();
  await dialog.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(dialog.getByLabel("Title", { exact: true })).toHaveValue("My current edit");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  // Navigation refreshes the selection while retaining tab-local private mode.
  await page.getByRole("button", { name: "Private mode on", exact: true }).last().click();
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByLabel(`Select ${changedTitle}`, { exact: true }).check();
  await page.getByRole("button", { name: "Move selected", exact: true }).click();
  const move = page.getByRole("dialog");
  await expect(move.getByRole("button", { name: "Confirm", exact: true })).toBeDisabled();
  await move.getByRole("checkbox", { name: /outside private mode/ }).check();
  await move.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByText(/1 moved; 0 failed/)).toBeVisible();
  await page.getByLabel("Bookmark folder", { exact: true }).selectOption("unsorted");
  await page.getByLabel(`Select ${changedTitle}`, { exact: true }).check();
  await page.getByRole("button", { name: "Delete selected", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByText(/1 moved to Trash; 0 failed/)).toBeVisible();
  await page.getByRole("button", { name: "Undo deletion", exact: true }).click();
  await expect(page.getByText(/1 restored; 0 could not/)).toBeVisible();
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(page.getByRole("button", { name: `Edit ${changedTitle}`, exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("home respects private favorites, tile visibility, and dashboard navigation", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const folder = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Home secrets ${Date.now()}`, parent: null, private: true } })).json();
  const title = `Private home ${Date.now()}`;
  const created = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/home", description: "", folder: folder.id } });
  const bookmark = await created.json();
  expect((await page.request.put(`/api/bookmarks/${bookmark.id}/favorite`, { headers: { ...headers, "If-Match": created.headers()["etag"] }, data: { favorite: true, after: null } })).ok()).toBeTruthy();
  await page.goto("/");
  const tile = page.getByRole("region", { name: "Bookmarks", exact: true });
  await expect(tile).toBeVisible(); await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await tile.getByRole("link", { name: "All of it", exact: true }).click();
  await expect(page).toHaveURL(/\/bookmarks$/);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByRole("navigation", { name: "The workspace" }).getByRole("link", { name: "Home", exact: true }).click();
  await expect(tile.getByRole("link", { name: new RegExp(title) })).toBeVisible();
  await page.getByRole("button", { name: "Private mode on", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.goto("/settings/home");
  await page.getByRole("button", { name: "Hide Bookmarks", exact: true }).click();
  await expect(page.getByRole("button", { name: "Show Bookmarks", exact: true })).toBeVisible();
  await page.goto("/"); await expect(page.getByRole("region", { name: "Tasks", exact: true })).toBeVisible(); await expect(tile).toHaveCount(0);
  await page.goto("/settings/home"); await page.getByRole("button", { name: "Show Bookmarks", exact: true }).click();
  await expect(page.getByRole("button", { name: "Hide Bookmarks", exact: true })).toBeVisible();
});

test("HTML transfer previews before writing and exports escaped inert data", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  await page.goto("/bookmarks/manage");
  const title = `Imported <guide> ${Date.now()}`;
  const html = `<DL><DT><H3>Import ${Date.now()}</H3><DL><DT><A HREF="https://example.com/import?x=1&amp;y=2">${title.replace("<", "&lt;").replace(">", "&gt;")}</A></DT><DD>Useful &amp; safe</DD><DT><A HREF="javascript:alert(1)">Rejected</A></DT></DL></DT></DL><script>window.importExecuted=true</script>`;
  await page.getByRole("button", { name: "Import HTML", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Bookmark HTML file", { exact: true }).setInputFiles({ name: "bookmarks.html", mimeType: "text/html", buffer: Buffer.from(html) });
  await dialog.getByRole("button", { name: "Preview import", exact: true }).click();
  await expect(dialog.getByText(/1 valid bookmarks, 1 folders/)).toBeVisible();
  await expect(dialog.getByText(/1 rejected/).first()).toBeVisible();
  const before = await page.request.get("/api/bookmarks", { params: { q: title.replace(/[<>]/g, "") } });
  expect((await before.json()).items).toHaveLength(0);
  await dialog.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("1 bookmarks imported");
  expect(await page.evaluate(() => Object.hasOwn(window, "importExecuted"))).toBeFalsy();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("link", { name: title, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Export HTML", exact: true }).click();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("dialog").getByRole("button", { name: "Download HTML", exact: true }).click();
  expect((await downloaded).suggestedFilename()).toBe("bookmarks.html");
  await expect(page.getByRole("dialog").getByRole("status")).toContainText("exported");
});

test("tags support keyboard filters and bulk changes without retaining private tag names", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const marker = `tagcheck${Date.now()}`;
  const folder = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: marker, parent: null, private: true } })).json();
  await page.request.post("/api/bookmarks", { headers, data: { title: marker, url: "https://example.com/tags", folder: folder.id, tags: [marker] } });
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto("/bookmarks/manage");
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByLabel("Filter tags (all selected)", { exact: true }).fill(marker);
  await page.getByLabel("Filter tags (all selected)", { exact: true }).press("Enter");
  await expect(page.getByRole("link", { name: marker, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Private mode on", exact: true }).last().click();
  await expect(page.getByRole("button", { name: `Remove tag ${marker}`, exact: true })).toHaveCount(0);
  expect(new URL(page.url()).searchParams.getAll("tag")).toHaveLength(0);
  for (const suffix of ["one", "two"]) {
    const created = await page.request.post("/api/bookmarks", { headers, data: { title: `${marker} ${suffix}`, url: `https://example.com/${suffix}`, tags: [] } });
    expect(created.ok()).toBeTruthy();
  }
  await page.goto(`/bookmarks/manage?q=${marker}`);
  for (const suffix of ["one", "two"]) await page.getByLabel(`Select ${marker} ${suffix}`, { exact: true }).check();
  await page.getByRole("button", { name: "Add tags to selected", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Tags", { exact: true }).fill("Project Work"); await dialog.getByLabel("Tags", { exact: true }).press("Enter");
  await dialog.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByText("2 updated; 0 failed.", { exact: false })).toBeVisible();
  await page.getByLabel("Filter tags (all selected)", { exact: true }).fill("project work"); await page.getByLabel("Filter tags (all selected)", { exact: true }).press("Enter");
  await expect(page.getByRole("table", { name: "Saved bookmarks" }).getByRole("link")).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("reading list survives opening and supports mark-read undo and combined filters", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  await page.goto("/bookmarks");
  const title = `Reading ${Date.now()}`;
  await page.getByRole("button", { name: "Add bookmark", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("URL", { exact: true }).fill("https://example.com/read");
  await dialog.getByLabel("Title", { exact: true }).fill(title);
  await dialog.getByLabel("Read later", { exact: true }).check();
  await dialog.getByRole("button", { name: "Add bookmark", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const section = page.getByRole("region", { name: /^Read later \(/ });
  const link = section.getByRole("link", { name: new RegExp(title) });
  await expect(link).toBeVisible();
  await page.context().route("https://example.com/**", (route) => route.fulfill({ body: "Reading target" }));
  const popup = page.waitForEvent("popup");
  const opened = page.waitForResponse((response) => response.url().endsWith("/open"));
  await link.click(); expect((await opened).ok()).toBeTruthy(); await (await popup).close();
  await expect(link).toBeVisible();
  await section.getByRole("button", { name: `Mark ${title} as read`, exact: true }).click();
  await expect(page.getByText(/1 marked as read; 0 failed/)).toBeVisible();
  await expect(link).toHaveCount(0);
  await page.getByRole("button", { name: "Undo mark as read", exact: true }).click();
  await expect(link).toBeVisible();
  await page.getByRole("link", { name: "See full reading list", exact: true }).click();
  await expect(page.getByLabel("Reading list only", { exact: true })).toBeChecked();
  await page.getByRole("searchbox", { name: "Search bookmarks", exact: true }).fill(title);
  await expect(page.getByRole("region", { name: "Reading list", exact: true }).getByRole("link", { name: new RegExp(title) })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("region", { name: "Reading list", exact: true }).getByRole("link", { name: new RegExp(title) })).toBeVisible();
});
