import { test, expect } from "@playwright/test";
import { signedIn, switchApplication } from "./theInstance";

test("saved links can be added, pinned, ordered and opened directly", async ({ page }) => {
  await signedIn(page);
  await switchApplication(page, "bookmarks", true);
  await page.goto("/bookmarks");
  const title = `Browser link ${Date.now()}`;
  await page.getByRole("button", { name: "Add bookmark", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("URL", { exact: true }).fill("https://example.com/bookmarks");
  await dialog.getByLabel("Title", { exact: true }).fill(title);
  await dialog.getByRole("button", { name: "Add bookmark", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const recent = page.getByRole("region", { name: "Recently added" });
  await recent.getByRole("button", { name: `Pin ${title}`, exact: true }).click();
  const favorite = page.getByRole("region", { name: "Favorites" });
  await expect(favorite.getByRole("link", { name: new RegExp(title) })).toHaveAttribute("href", "https://example.com/bookmarks");
  await expect(favorite.getByRole("button", { name: `Move ${title} later`, exact: true })).toBeVisible();
  // Stop at the target boundary; recording must still happen independently.
  await page.context().route("https://example.com/**", (route) => route.fulfill({ body: "Saved link target" }));
  const recorded = page.waitForResponse((response) => response.url().endsWith("/open") && response.request().method() === "POST");
  const popup = page.waitForEvent("popup");
  await favorite.getByRole("link", { name: new RegExp(title) }).click();
  expect((await recorded).ok()).toBeTruthy();
  await (await popup).close();
});

test("private mode clears private cards and resets on reload at phone width", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const folderResponse = await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Private ${Date.now()}`, parent: null, private: true } });
  expect(folderResponse.ok()).toBeTruthy();
  const folder = await folderResponse.json();
  const title = `Hidden browser link ${Date.now()}`;
  const created = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/private", description: "", folder: folder.id } });
  expect(created.ok()).toBeTruthy();
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto("/bookmarks");
  await expect(page.getByRole("heading", { name: "Recently added" })).toBeVisible();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole("button", { name: "Private mode on", exact: true }).last().click();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Private mode off", exact: true })).toBeVisible();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
});

test("management preserves private inheritance, checks stale edits, and restores deletions", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const parent = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Private tree ${Date.now()}`, parent: null, private: true } })).json();
  const child = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: "Inherited", parent: parent.id, private: false } })).json();
  const title = `Managed link ${Date.now()}`;
  const create = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/" + "long-path".repeat(60), description: "", folder: child.id } });
  expect(create.ok()).toBeTruthy(); const bookmark = await create.json();
  await page.goto("/bookmarks/manage");
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByLabel("Bookmark folder", { exact: true }).selectOption(child.id);
  await expect(page.getByText(/Private \(inherited\)/)).toBeVisible();
  await page.getByRole("button", { name: `Edit ${title}`, exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Title", { exact: true }).fill("My current edit");
  const other = await page.request.put(`/api/bookmarks/${bookmark.id}`, { headers: { ...headers, "If-Match": create.headers()["etag"] }, data: { title: "Changed elsewhere", url: bookmark.url, description: "", folder: child.id } });
  expect(other.ok()).toBeTruthy();
  await dialog.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(dialog.getByLabel("Title", { exact: true })).toHaveValue("My current edit");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  // Navigation refreshes the selection while retaining tab-local private mode.
  await page.getByRole("button", { name: "Private mode on", exact: true }).last().click();
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByLabel("Select Changed elsewhere", { exact: true }).check();
  await page.getByRole("button", { name: "Move selected", exact: true }).click();
  const move = page.getByRole("dialog");
  await expect(move.getByRole("button", { name: "Confirm", exact: true })).toBeDisabled();
  await move.getByRole("checkbox", { name: /outside private mode/ }).check();
  await move.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByText(/1 moved; 0 failed/)).toBeVisible();
  await page.getByLabel("Bookmark folder", { exact: true }).selectOption("unsorted");
  await page.getByLabel("Select Changed elsewhere", { exact: true }).check();
  await page.getByRole("button", { name: "Delete selected", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByText(/1 moved to Trash; 0 failed/)).toBeVisible();
  await page.getByRole("button", { name: "Undo deletion", exact: true }).click();
  await expect(page.getByText(/1 restored; 0 could not/)).toBeVisible();
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(page.getByRole("button", { name: "Edit Changed elsewhere", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("home respects private favorites, tile visibility, and dashboard navigation", async ({ page }) => {
  await signedIn(page); await switchApplication(page, "bookmarks", true);
  const headers = { "X-Personalaffe-CSRF": "1", Origin: new URL(page.url()).origin, "Personalaffe-Private": "true" };
  const folder = await (await page.request.post("/api/bookmarks/folders", { headers, data: { name: `Home secrets ${Date.now()}`, parent: null, private: true } })).json();
  const title = `Private home ${Date.now()}`;
  const created = await page.request.post("/api/bookmarks", { headers, data: { title, url: "https://example.com/home", description: "", folder: folder.id } });
  const bookmark = await created.json();
  expect((await page.request.put(`/api/bookmarks/${bookmark.id}/favorite`, { headers: { ...headers, "If-Match": created.headers()["etag"] }, data: { favorite: true, after: null } })).ok()).toBeTruthy();
  await page.goto("/");
  const tile = page.getByRole("region", { name: "Bookmarks", exact: true });
  await expect(tile).toBeVisible(); await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await tile.getByRole("link", { name: "All of it", exact: true }).click();
  await expect(page).toHaveURL(/\/bookmarks$/);
  await page.getByRole("button", { name: "Private mode off", exact: true }).click();
  await page.getByRole("navigation", { name: "The workspace" }).getByRole("link", { name: "Home", exact: true }).click();
  await expect(tile.getByRole("link", { name: new RegExp(title) })).toBeVisible();
  await page.getByRole("button", { name: "Private mode on", exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.goto("/settings/home");
  await page.getByRole("button", { name: "Hide Bookmarks", exact: true }).click();
  await expect(page.getByRole("button", { name: "Show Bookmarks", exact: true })).toBeVisible();
  await page.goto("/"); await expect(page.getByRole("region", { name: "Tasks", exact: true })).toBeVisible(); await expect(tile).toHaveCount(0);
  await page.goto("/settings/home"); await page.getByRole("button", { name: "Show Bookmarks", exact: true }).click();
  await expect(page.getByRole("button", { name: "Hide Bookmarks", exact: true })).toBeVisible();
});
